import React, { useState } from 'react';
import { X, Printer, Copy, Check, FileText, ShieldCheck, Sparkles, Building2 } from 'lucide-react';
import { CalculatorMeta } from '../types';

interface SharePrintPdfModalProps {
  isOpen: boolean;
  onClose: () => void;
  calculator?: CalculatorMeta;
  calculationDetails?: {
    title: string;
    inputs: Record<string, any>;
    results: Record<string, any>;
    summaryText: string;
    formula?: string;
  };
}

export const SharePrintPdfModal: React.FC<SharePrintPdfModalProps> = ({
  isOpen,
  onClose,
  calculator,
  calculationDetails
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const title = calculationDetails?.title || calculator?.name || 'RZ® Commercial Calculation Sheet';
  const formula = calculationDetails?.formula || calculator?.formula || 'Analytical Formula Standard';
  const currentDate = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const lines = [
      `=== ${title} ===`,
      `Generated by RZ® Calculator • Free Public Platform`,
      `Timestamp: ${currentDate}`,
      `Formula: ${formula}`,
      `\n[INPUTS]`,
      ...Object.entries(calculationDetails?.inputs || {}).map(([k, v]) => `• ${k}: ${v}`),
      `\n[RESULTS]`,
      ...Object.entries(calculationDetails?.results || {}).map(([k, v]) => `• ${k}: ${v}`),
      `\nSummary: ${calculationDetails?.summaryText || ''}`,
      `\nVerification: Verified by RZ® MINETRIX 64-Bit Simulation Sandbox`
    ].join('\n');

    navigator.clipboard?.writeText(lines);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-2xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in fade-in zoom-in-95 duration-200">
        {/* Modal Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center font-bold font-mono">
              RZ
            </div>
            <div>
              <h3 className="font-bold text-white text-sm">Official Calculation Slip &amp; Print Preview</h3>
              <p className="text-[11px] text-slate-500 font-mono">Document #RZ-CALC-{Date.now().toString().slice(-6)}</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs flex items-center gap-1.5 transition cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Slip</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Voucher Paper */}
        <div className="p-6 overflow-y-auto space-y-6 bg-slate-900">
          <div className="bg-white text-slate-900 rounded-2xl p-6 shadow-md border border-slate-200 space-y-5 print:p-0 print:border-none print:shadow-none">
            {/* Slip Header */}
            <div className="flex items-start justify-between border-b border-slate-200 pb-4">
              <div>
                <div className="text-xl font-black tracking-tight text-slate-950">
                  RZ® MINETRIX
                </div>
                <div className="text-xs font-semibold text-amber-700 uppercase tracking-wider">
                  Public Engineering &amp; Commercial Calculator
                </div>
                <div className="text-[11px] text-slate-500 mt-0.5">
                  Platform #10 &bull; Free Cloud Utility Gateway
                </div>
              </div>

              <div className="text-right text-xs font-mono text-slate-500">
                <div>Date: {currentDate}</div>
                <div className="text-[10px] text-emerald-700 font-bold mt-1">STATUS: CERTIFIED RUN</div>
              </div>
            </div>

            {/* Document Subject */}
            <div>
              <span className="text-[10px] font-mono uppercase tracking-wider text-slate-400 block">
                Calculation Sheet Subject
              </span>
              <h2 className="text-lg font-bold text-slate-900">{title}</h2>
              {calculator?.description && (
                <p className="text-xs text-slate-600 mt-1">{calculator.description}</p>
              )}
            </div>

            {/* Formula Applied */}
            <div className="p-3 rounded-xl bg-slate-100 border border-slate-200 text-xs font-mono">
              <span className="text-[10px] text-slate-500 block uppercase font-bold mb-0.5">
                Mathematical Rule / Formula Applied:
              </span>
              <div className="text-slate-800 font-bold">{formula}</div>
            </div>

            {/* Input & Output Ledger */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Inputs */}
              <div className="space-y-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block border-b border-slate-200 pb-1">
                  Input Parameters
                </span>
                <div className="space-y-1 text-xs font-mono">
                  {Object.entries(calculationDetails?.inputs || { 'Base Value': 'Standard Demo Run' }).map(([k, v]) => (
                    <div key={k} className="flex justify-between py-1 border-b border-slate-100">
                      <span className="text-slate-600 capitalize">{k}:</span>
                      <span className="font-bold text-slate-900">{String(v)}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Results */}
              <div className="space-y-2">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block border-b border-slate-200 pb-1">
                  Computed Results
                </span>
                <div className="space-y-1 text-xs font-mono">
                  {Object.entries(calculationDetails?.results || { 'Outcome': calculationDetails?.summaryText || 'Computed with 64-bit precision' }).map(([k, v]) => (
                    <div key={k} className="flex justify-between py-1 border-b border-slate-100">
                      <span className="text-slate-600 capitalize">{k}:</span>
                      <span className="font-bold text-emerald-700">{String(v)}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Slip Footer */}
            <div className="border-t border-slate-200 pt-4 flex flex-col sm:flex-row items-center justify-between text-[11px] text-slate-500 gap-2">
              <div className="flex items-center gap-1.5">
                <ShieldCheck className="w-4 h-4 text-emerald-600" />
                <span>RZ® Free Public Utility Gateway. Independent operational estimate.</span>
              </div>
              <div className="font-mono text-[10px]">
                https://minetrix.rz.app
              </div>
            </div>
          </div>
        </div>

        {/* Modal Footer Controls */}
        <div className="p-4 border-t border-slate-800 bg-slate-950 flex items-center justify-between">
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-bold text-slate-300 hover:text-white flex items-center gap-1.5 transition cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied to Clipboard' : 'Copy Text Summary'}</span>
          </button>

          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-bold text-white transition cursor-pointer"
          >
            Close Preview
          </button>
        </div>
      </div>
    </div>
  );
};
