import {
  Employee,
  Department,
  Designation,
  Shift,
  AttendanceEntry,
  LeaveRequest,
  OvertimeEntry,
  SalarySetupItem,
  PayrollRecord,
  StaffAdvance,
  BattaEntry,
  StaffDocument,
  WorkforceApproval
} from './types';

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'DEP-01', name: 'Administration', manager: 'Nafid Khan (MD)', employeeCount: 8, activeCount: 8, status: 'Active', description: 'Executive oversight, legal compliance, and office management', budgetAllocated: 1200000 },
  { id: 'DEP-02', name: 'Accounts & Finance', manager: 'Anjali Menon', employeeCount: 10, activeCount: 10, status: 'Active', description: 'Financial reporting, general ledgers, payroll, and tax audits', budgetAllocated: 1800000 },
  { id: 'DEP-03', name: 'Human Resources (HR)', manager: 'Sunita Rao', employeeCount: 6, activeCount: 6, status: 'Active', description: 'Workforce recruitment, staff compliance, welfare, and training', budgetAllocated: 950000 },
  { id: 'DEP-04', name: 'Quarry Operations', manager: 'Rajesh Nair', employeeCount: 32, activeCount: 30, status: 'Active', description: 'Pithead extraction, blasting, excavator ops, and safety protocols', budgetAllocated: 4500000 },
  { id: 'DEP-05', name: 'Crusher Plant', manager: 'Mustafa K.', employeeCount: 26, activeCount: 25, status: 'Active', description: 'Crusher feeding, VSI sand processing, grading, screening, and plant upkeep', budgetAllocated: 3800000 },
  { id: 'DEP-06', name: 'Vehicle & Fleet Logistics', manager: 'Babu Moopan', employeeCount: 28, activeCount: 27, status: 'Active', description: 'Tipper fleet, driver rosters, trip dispatch, diesel tracking, and maintenance', budgetAllocated: 4200000 },
  { id: 'DEP-07', name: 'Sales & Commercial', manager: 'Vikram Seth', employeeCount: 9, activeCount: 9, status: 'Active', description: 'Customer orders, quotations, aggregate dispatches, and key client relations', budgetAllocated: 1400000 },
  { id: 'DEP-08', name: 'Purchase & Procurement', manager: 'K. Sukumaran', employeeCount: 5, activeCount: 5, status: 'Active', description: 'Explosives, diesel fuel, plant spare parts, lubricants, and conveyor belts', budgetAllocated: 1100000 },
  { id: 'DEP-09', name: 'Central Store & Inventory', manager: 'P. Hariharan', employeeCount: 4, activeCount: 4, status: 'Active', description: 'Weighbridge spare parts, tools, grease inventory, and consumables check', budgetAllocated: 750000 },
  { id: 'DEP-10', name: 'Dispatch & Weighbridge', manager: 'Kiran Dev', employeeCount: 7, activeCount: 7, status: 'Active', description: 'Automated tare scale weighments, gate passes, QR scanning, and delivery notes', budgetAllocated: 850000 },
  { id: 'DEP-11', name: 'Marketing & Brand Relations', manager: 'Deepa Roy', employeeCount: 3, activeCount: 3, status: 'Active', description: 'Dealer network promotions, builder outreach, digital presence, and PR', budgetAllocated: 600000 },
  { id: 'DEP-12', name: 'Contract & Civil Jobs', manager: 'Arshad Ali', employeeCount: 6, activeCount: 5, status: 'Active', description: 'Site subcontracts, highway sub-base supply, road laying, and earthwork', budgetAllocated: 2100000 },
  { id: 'DEP-13', name: 'Customer Support & Helpdesk', manager: 'Pooja Pillai', employeeCount: 4, activeCount: 4, status: 'Active', description: 'Delivery tracking, contractor invoice queries, and customer satisfaction', budgetAllocated: 550000 },
  { id: 'DEP-14', name: 'Plant Operations & Engineering', manager: 'Eng. Sudheer Babu', employeeCount: 5, activeCount: 5, status: 'Active', description: 'Generator maintenance, HT transformer checks, electrical safety, and uptime', budgetAllocated: 1600000 }
];

export const MOCK_DESIGNATIONS: Designation[] = [
  { id: 'DES-01', name: 'General Manager - Operations', department: 'Administration', grade: 'Executive', salaryType: 'Monthly Salary', defaultSalary: 85000, overtimeEligible: false, battaEligible: true, status: 'Active' },
  { id: 'DES-02', name: 'Chief Financial Comptroller', department: 'Accounts & Finance', grade: 'Executive', salaryType: 'Monthly Salary', defaultSalary: 75000, overtimeEligible: false, battaEligible: false, status: 'Active' },
  { id: 'DES-03', name: 'Senior Accountant', department: 'Accounts & Finance', grade: 'A', salaryType: 'Monthly Salary', defaultSalary: 38000, overtimeEligible: true, battaEligible: false, status: 'Active' },
  { id: 'DES-04', name: 'Quarry Pithead Supervisor', department: 'Quarry Operations', grade: 'B', salaryType: 'Monthly Salary', defaultSalary: 28000, overtimeEligible: true, battaEligible: true, status: 'Active' },
  { id: 'DES-05', name: 'Licensed Mining Blaster', department: 'Quarry Operations', grade: 'B', salaryType: 'Monthly Salary', defaultSalary: 35000, overtimeEligible: true, battaEligible: true, status: 'Active' },
  { id: 'DES-06', name: 'Heavy Excavator Operator', department: 'Quarry Operations', grade: 'C', salaryType: 'Daily Wage', defaultSalary: 1100, overtimeEligible: true, battaEligible: true, status: 'Active' },
  { id: 'DES-07', name: 'Crusher Plant Master Tech', department: 'Crusher Plant', grade: 'B', salaryType: 'Monthly Salary', defaultSalary: 32000, overtimeEligible: true, battaEligible: true, status: 'Active' },
  { id: 'DES-08', name: 'VSI Sand Screen Operator', department: 'Crusher Plant', grade: 'C', salaryType: 'Daily Wage', defaultSalary: 950, overtimeEligible: true, battaEligible: true, status: 'Active' },
  { id: 'DES-09', name: 'Heavy Tipper Multi-Axle Driver', department: 'Vehicle & Fleet Logistics', grade: 'C', salaryType: 'Monthly Salary', defaultSalary: 22000, overtimeEligible: true, battaEligible: true, status: 'Active' },
  { id: 'DES-10', name: 'Fleet Maintenance Mechanic', department: 'Vehicle & Fleet Logistics', grade: 'B', salaryType: 'Monthly Salary', defaultSalary: 26000, overtimeEligible: true, battaEligible: false, status: 'Active' },
  { id: 'DES-11', name: 'Weighbridge & Gate Officer', department: 'Dispatch & Weighbridge', grade: 'C', salaryType: 'Monthly Salary', defaultSalary: 21000, overtimeEligible: true, battaEligible: false, status: 'Active' },
  { id: 'DES-12', name: 'Commercial Sales Executive', department: 'Sales & Commercial', grade: 'B', salaryType: 'Monthly Salary', defaultSalary: 30000, overtimeEligible: false, battaEligible: true, status: 'Active' },
  { id: 'DES-13', name: 'Civil Site Project Engineer', department: 'Contract & Civil Jobs', grade: 'A', salaryType: 'Monthly Salary', defaultSalary: 45000, overtimeEligible: true, battaEligible: true, status: 'Active' },
  { id: 'DES-14', name: 'Store Keeper & Inventory Lead', department: 'Central Store & Inventory', grade: 'C', salaryType: 'Monthly Salary', defaultSalary: 23000, overtimeEligible: true, battaEligible: false, status: 'Active' }
];

export const MOCK_SHIFTS: Shift[] = [
  { id: 'SHF-01', name: 'General Office Shift', startTime: '09:00 AM', endTime: '05:30 PM', breakDuration: '45 mins', gracePeriod: '15 mins', overtimeRule: '1.5x after 8.0 hrs', department: 'Administration', status: 'Active', assignedStaffCount: 22 },
  { id: 'SHF-02', name: 'Quarry Pithead Morning Shift', startTime: '06:30 AM', endTime: '02:30 PM', breakDuration: '30 mins', gracePeriod: '10 mins', overtimeRule: '2.0x for emergency blasting', department: 'Quarry Operations', status: 'Active', assignedStaffCount: 28 },
  { id: 'SHF-03', name: 'Quarry Afternoon Shift', startTime: '02:30 PM', endTime: '10:30 PM', breakDuration: '30 mins', gracePeriod: '10 mins', overtimeRule: '1.5x regular overtime', department: 'Quarry Operations', status: 'Active', assignedStaffCount: 14 },
  { id: 'SHF-04', name: 'Crusher Plant Day Shift', startTime: '07:00 AM', endTime: '04:00 PM', breakDuration: '60 mins', gracePeriod: '15 mins', overtimeRule: '1.5x rate per hour', department: 'Crusher Plant', status: 'Active', assignedStaffCount: 18 },
  { id: 'SHF-05', name: 'Crusher Plant Night Shift', startTime: '08:00 PM', endTime: '05:00 AM', breakDuration: '60 mins', gracePeriod: '15 mins', overtimeRule: '1.75x night differential', department: 'Crusher Plant', status: 'Active', assignedStaffCount: 8 },
  { id: 'SHF-06', name: 'Fleet Haulage & Driver Shift', startTime: '05:30 AM', endTime: '03:30 PM', breakDuration: '60 mins', gracePeriod: '20 mins', overtimeRule: 'Standard Batta + Hourly OT', department: 'Vehicle & Fleet Logistics', status: 'Active', assignedStaffCount: 28 },
  { id: 'SHF-07', name: 'Weighbridge Continuous Shift A', startTime: '06:00 AM', endTime: '02:00 PM', breakDuration: '30 mins', gracePeriod: '5 mins', overtimeRule: 'Straight OT allowance', department: 'Dispatch & Weighbridge', status: 'Active', assignedStaffCount: 4 }
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'EMP-001',
    name: 'Rajesh Nair',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Quarry Operations',
    designation: 'Quarry Pithead Supervisor',
    role: 'SUPERVISOR',
    branch: 'Calicut Laterite Concession #1',
    joiningDate: '2022-01-12',
    salaryType: 'Monthly Salary',
    salaryRate: 28000,
    status: 'Active',
    phone: '+91 98471 22334',
    email: 'rajesh.nair@malabarmining.com',
    gender: 'Male',
    dob: '1984-06-15',
    address: 'Hill View House, Kinaloor PO, Calicut, Kerala - 673612',
    emergencyContact: { name: 'Sujatha Nair', relation: 'Spouse', phone: '+91 98471 99881' },
    reportingManager: 'Nafid Khan (MD)',
    employmentType: 'Full Time',
    overtimeRate: 180,
    battaEligible: true,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'Federal Bank', accountNo: '14200100492831', ifsc: 'FDRL0001420', branch: 'Balussery' },
    attendanceThisMonth: 23,
    leaveBalance: 14,
    advanceBalance: 4000,
    pendingSalary: 0,
    documentsCount: 6
  },
  {
    id: 'EMP-002',
    name: 'Mustafa K.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Crusher Plant',
    designation: 'Crusher Plant Master Tech',
    role: 'OPERATOR',
    branch: 'Wayanad VSI Sand Plant',
    joiningDate: '2023-03-04',
    salaryType: 'Monthly Salary',
    salaryRate: 32000,
    status: 'Active',
    phone: '+91 94472 88192',
    email: 'mustafa.k@malabarmining.com',
    gender: 'Male',
    dob: '1989-11-20',
    address: 'Kakkavayal Road, Meppadi, Wayanad, Kerala - 673577',
    emergencyContact: { name: 'Amina Mustafa', relation: 'Spouse', phone: '+91 94472 11094' },
    reportingManager: 'Eng. Sudheer Babu',
    employmentType: 'Full Time',
    overtimeRate: 200,
    battaEligible: true,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'HDFC Bank', accountNo: '50100239108422', ifsc: 'HDFC0001844', branch: 'Kalpetta' },
    attendanceThisMonth: 22,
    leaveBalance: 11,
    advanceBalance: 1500,
    pendingSalary: 0,
    documentsCount: 5
  },
  {
    id: 'EMP-003',
    name: 'Arun Varma',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    department: 'Vehicle & Fleet Logistics',
    designation: 'Heavy Tipper Multi-Axle Driver',
    role: 'DRIVER',
    branch: 'Malabar Fleet Depot',
    joiningDate: '2021-08-15',
    salaryType: 'Monthly Salary',
    salaryRate: 22000,
    status: 'Active',
    phone: '+91 99951 10293',
    email: 'arun.driver@malabarmining.com',
    gender: 'Male',
    dob: '1991-04-08',
    address: 'Puthiyangadi, Kozhikode, Kerala - 673021',
    emergencyContact: { name: 'Karthika Varma', relation: 'Sister', phone: '+91 99951 77211' },
    reportingManager: 'Babu Moopan',
    employmentType: 'Full Time',
    overtimeRate: 150,
    battaEligible: true,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'State Bank of India', accountNo: '30492817492', ifsc: 'SBIN0008492', branch: 'Kozhikode Main' },
    attendanceThisMonth: 24,
    leaveBalance: 9,
    advanceBalance: 5000,
    pendingSalary: 0,
    documentsCount: 7
  },
  {
    id: 'EMP-004',
    name: 'Anjali Menon',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Accounts & Finance',
    designation: 'Senior Accountant',
    role: 'ACCOUNTANT',
    branch: 'Corporate HQ Calicut',
    joiningDate: '2021-02-01',
    salaryType: 'Monthly Salary',
    salaryRate: 38000,
    status: 'Active',
    phone: '+91 97455 33412',
    email: 'anjali.accounts@malabarmining.com',
    gender: 'Female',
    dob: '1993-08-25',
    address: 'Thiruthiyad, Calicut, Kerala - 673004',
    emergencyContact: { name: 'Dr. Vivek Menon', relation: 'Spouse', phone: '+91 97455 44891' },
    reportingManager: 'Nafid Khan (MD)',
    employmentType: 'Full Time',
    overtimeRate: 240,
    battaEligible: false,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'HDFC Bank', accountNo: '50100492817263', ifsc: 'HDFC0000188', branch: 'Mavoor Road Calicut' },
    attendanceThisMonth: 23,
    leaveBalance: 16,
    advanceBalance: 0,
    pendingSalary: 0,
    documentsCount: 8
  },
  {
    id: 'EMP-005',
    name: 'Suresh Babu',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    department: 'Quarry Operations',
    designation: 'Heavy Excavator Operator',
    role: 'OPERATOR',
    branch: 'Calicut Laterite Concession #1',
    joiningDate: '2022-06-10',
    salaryType: 'Daily Wage',
    salaryRate: 1100,
    status: 'Active',
    phone: '+91 98460 77123',
    email: 'suresh.operator@malabarmining.com',
    gender: 'Male',
    dob: '1987-03-12',
    address: 'Ulliyeri, Kozhikode, Kerala - 673323',
    emergencyContact: { name: 'Geetha Babu', relation: 'Spouse', phone: '+91 98460 22345' },
    reportingManager: 'Rajesh Nair',
    employmentType: 'Daily Wage',
    overtimeRate: 175,
    battaEligible: true,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'Federal Bank', accountNo: '14200293847111', ifsc: 'FDRL0001420', branch: 'Balussery' },
    attendanceThisMonth: 21,
    leaveBalance: 6,
    advanceBalance: 2000,
    pendingSalary: 0,
    documentsCount: 4
  },
  {
    id: 'EMP-006',
    name: 'Kiran Dev',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Dispatch & Weighbridge',
    designation: 'Weighbridge & Gate Officer',
    role: 'STAFF',
    branch: 'Calicut Laterite Concession #1',
    joiningDate: '2023-01-15',
    salaryType: 'Monthly Salary',
    salaryRate: 21000,
    status: 'Active',
    phone: '+91 94461 44556',
    email: 'kiran.weigh@malabarmining.com',
    gender: 'Male',
    dob: '1995-10-02',
    address: 'Atholi, Kozhikode, Kerala - 673315',
    emergencyContact: { name: 'Raghavan Dev', relation: 'Father', phone: '+91 94461 88990' },
    reportingManager: 'Vikram Seth',
    employmentType: 'Full Time',
    overtimeRate: 140,
    battaEligible: false,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'State Bank of India', accountNo: '30928172635', ifsc: 'SBIN0008492', branch: 'Kozhikode Main' },
    attendanceThisMonth: 23,
    leaveBalance: 12,
    advanceBalance: 1000,
    pendingSalary: 0,
    documentsCount: 5
  },
  {
    id: 'EMP-007',
    name: 'Sunita Rao',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources (HR)',
    designation: 'HR Manager & Compliance Lead',
    role: 'HR',
    branch: 'Corporate HQ Calicut',
    joiningDate: '2021-05-18',
    salaryType: 'Monthly Salary',
    salaryRate: 46000,
    status: 'Active',
    phone: '+91 97471 22910',
    email: 'sunita.hr@malabarmining.com',
    gender: 'Female',
    dob: '1988-01-30',
    address: 'Palazhi, Calicut, Kerala - 673014',
    emergencyContact: { name: 'Girish Rao', relation: 'Brother', phone: '+91 97471 44882' },
    reportingManager: 'Nafid Khan (MD)',
    employmentType: 'Full Time',
    overtimeRate: 250,
    battaEligible: false,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'HDFC Bank', accountNo: '50100994827163', ifsc: 'HDFC0000188', branch: 'Mavoor Road Calicut' },
    attendanceThisMonth: 23,
    leaveBalance: 18,
    advanceBalance: 0,
    pendingSalary: 0,
    documentsCount: 7
  },
  {
    id: 'EMP-008',
    name: 'Muhammed Shafi',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Quarry Operations',
    designation: 'Licensed Mining Blaster',
    role: 'SUPERVISOR',
    branch: 'Calicut Laterite Concession #1',
    joiningDate: '2022-09-01',
    salaryType: 'Monthly Salary',
    salaryRate: 35000,
    status: 'Active',
    phone: '+91 98475 66778',
    email: 'shafi.blaster@malabarmining.com',
    gender: 'Male',
    dob: '1982-12-14',
    address: 'Koduvally, Kozhikode, Kerala - 673572',
    emergencyContact: { name: 'Jameela Shafi', relation: 'Spouse', phone: '+91 98475 11223' },
    reportingManager: 'Rajesh Nair',
    employmentType: 'Full Time',
    overtimeRate: 220,
    battaEligible: true,
    paymentMode: 'Bank Transfer',
    bankDetails: { bankName: 'Federal Bank', accountNo: '14200883920192', ifsc: 'FDRL0001420', branch: 'Balussery' },
    attendanceThisMonth: 22,
    leaveBalance: 8,
    advanceBalance: 6000,
    pendingSalary: 0,
    documentsCount: 6
  }
];

export const MOCK_ATTENDANCE_ENTRIES: AttendanceEntry[] = [
  { id: 'ATT-001', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', date: '2026-03-24', shift: 'Quarry Pithead Morning Shift', checkIn: '06:24 AM', checkOut: '03:15 PM', status: 'Present', workingHours: 8.8, overtimeHours: 0.8, lateMinutes: 0, remarks: 'On time. Morning safety drill completed.' },
  { id: 'ATT-002', employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', date: '2026-03-24', shift: 'Crusher Plant Day Shift', checkIn: '06:55 AM', checkOut: '04:45 PM', status: 'Overtime', workingHours: 9.7, overtimeHours: 1.7, lateMinutes: 0, remarks: 'VSI Sand rotor bearing inspection completed.' },
  { id: 'ATT-003', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', date: '2026-03-24', shift: 'Fleet Haulage & Driver Shift', checkIn: '05:45 AM', checkOut: '04:00 PM', status: 'Present', workingHours: 10.2, overtimeHours: 1.2, lateMinutes: 15, remarks: 'Trip KL-11-BH-9821 to Kochi Highway bypass.' },
  { id: 'ATT-004', employeeId: 'EMP-004', employeeName: 'Anjali Menon', department: 'Accounts & Finance', date: '2026-03-24', shift: 'General Office Shift', checkIn: '08:58 AM', checkOut: '05:35 PM', status: 'Present', workingHours: 8.6, overtimeHours: 0.0, lateMinutes: 0, remarks: 'Bank reconciliation audit completed.' },
  { id: 'ATT-005', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', date: '2026-03-24', shift: 'Quarry Pithead Morning Shift', checkIn: '06:40 AM', checkOut: '02:30 PM', status: 'Late', workingHours: 7.8, overtimeHours: 0.0, lateMinutes: 10, remarks: 'Late by 10 mins due to rain delay on approach road.' },
  { id: 'ATT-006', employeeId: 'EMP-006', employeeName: 'Kiran Dev', department: 'Dispatch & Weighbridge', date: '2026-03-24', shift: 'Weighbridge Continuous Shift A', checkIn: '05:58 AM', checkOut: '02:10 PM', status: 'Present', workingHours: 8.2, overtimeHours: 0.2, lateMinutes: 0, remarks: 'Handled 48 aggregate weighments cleanly.' },
  { id: 'ATT-007', employeeId: 'EMP-007', employeeName: 'Sunita Rao', department: 'Human Resources (HR)', date: '2026-03-24', shift: 'General Office Shift', checkIn: '09:05 AM', checkOut: '05:30 PM', status: 'Present', workingHours: 8.4, overtimeHours: 0.0, lateMinutes: 5, remarks: 'Processed 3 staff health insurance renewals.' },
  { id: 'ATT-008', employeeId: 'EMP-008', employeeName: 'Muhammed Shafi', department: 'Quarry Operations', date: '2026-03-24', shift: 'Quarry Pithead Morning Shift', checkIn: '-', checkOut: '-', status: 'Leave', workingHours: 0.0, overtimeHours: 0.0, lateMinutes: 0, remarks: 'Approved Casual Leave for family ceremony.' }
];

export const MOCK_LEAVE_REQUESTS: LeaveRequest[] = [
  { id: 'LEV-101', employeeId: 'EMP-008', employeeName: 'Muhammed Shafi', department: 'Quarry Operations', leaveType: 'Casual Leave', fromDate: '2026-03-24', toDate: '2026-03-25', days: 2, reason: 'Family wedding ceremony at hometown', status: 'Approved', approver: 'Sunita Rao (HR)', appliedDate: '2026-03-21' },
  { id: 'LEV-102', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', leaveType: 'Sick Leave', fromDate: '2026-03-27', toDate: '2026-03-28', days: 2, reason: 'Viral fever and medical consultation', status: 'Pending', approver: 'Rajesh Nair', appliedDate: '2026-03-23' },
  { id: 'LEV-103', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', leaveType: 'Annual Leave', fromDate: '2026-04-02', toDate: '2026-04-06', days: 5, reason: 'Vishu festival holiday travel with family', status: 'Pending', approver: 'Babu Moopan', appliedDate: '2026-03-22' },
  { id: 'LEV-104', employeeId: 'EMP-006', employeeName: 'Kiran Dev', department: 'Dispatch & Weighbridge', leaveType: 'Emergency Leave', fromDate: '2026-03-10', toDate: '2026-03-11', days: 2, reason: 'Father hospital admission for checkup', status: 'Approved', approver: 'Sunita Rao (HR)', appliedDate: '2026-03-09' }
];

export const MOCK_OVERTIME_ENTRIES: OvertimeEntry[] = [
  { id: 'OT-001', employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', date: '2026-03-24', regularHours: 8.0, overtimeHours: 1.7, rate: 200, amount: 340, status: 'Pending' },
  { id: 'OT-002', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', date: '2026-03-24', regularHours: 8.0, overtimeHours: 1.2, rate: 150, amount: 180, status: 'Approved', approvedBy: 'Babu Moopan' },
  { id: 'OT-003', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', date: '2026-03-24', regularHours: 8.0, overtimeHours: 0.8, rate: 180, amount: 144, status: 'Approved', approvedBy: 'Nafid Khan (MD)' },
  { id: 'OT-004', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', date: '2026-03-23', regularHours: 8.0, overtimeHours: 2.5, rate: 175, amount: 437.5, status: 'Approved', approvedBy: 'Rajesh Nair' }
];

export const MOCK_SALARY_SETUP: SalarySetupItem[] = [
  { employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', salaryType: 'Monthly Salary', basicSalary: 28000, monthlySalary: 28000, overtimeRate: 180, battaRate: 350, fixedAllowance: 3000, statutoryDeductions: 1800, bonusPercentage: 8.33, advanceDeductionPlan: 1000 },
  { employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', salaryType: 'Monthly Salary', basicSalary: 32000, monthlySalary: 32000, overtimeRate: 200, battaRate: 400, fixedAllowance: 3500, statutoryDeductions: 2100, bonusPercentage: 8.33, advanceDeductionPlan: 1000 },
  { employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', salaryType: 'Monthly Salary', basicSalary: 22000, monthlySalary: 22000, overtimeRate: 150, battaRate: 600, fixedAllowance: 2000, statutoryDeductions: 1500, bonusPercentage: 8.33, advanceDeductionPlan: 1500 },
  { employeeId: 'EMP-004', employeeName: 'Anjali Menon', department: 'Accounts & Finance', salaryType: 'Monthly Salary', basicSalary: 38000, monthlySalary: 38000, overtimeRate: 240, battaRate: 0, fixedAllowance: 5000, statutoryDeductions: 2500, bonusPercentage: 10.0, advanceDeductionPlan: 0 },
  { employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', salaryType: 'Daily Wage', basicSalary: 24200, dailyRate: 1100, overtimeRate: 175, battaRate: 300, fixedAllowance: 1500, statutoryDeductions: 1200, bonusPercentage: 8.33, advanceDeductionPlan: 1000 }
];

export const MOCK_PAYROLL_RECORDS: PayrollRecord[] = [
  { id: 'PAY-2026-03-01', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', designation: 'Quarry Pithead Supervisor', month: 'March 2026', workingDays: 26, basic: 28000, overtime: 1840, batta: 4200, allowances: 3000, advanceDeduction: 1000, otherDeductions: 1800, grossSalary: 37040, netSalary: 34240, status: 'Approved', paymentMode: 'Bank Transfer' },
  { id: 'PAY-2026-03-02', employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', designation: 'Crusher Plant Master Tech', month: 'March 2026', workingDays: 25, basic: 32000, overtime: 2400, batta: 4800, allowances: 3500, advanceDeduction: 1000, otherDeductions: 2100, grossSalary: 42700, netSalary: 39600, status: 'Calculated', paymentMode: 'Bank Transfer' },
  { id: 'PAY-2026-03-03', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', designation: 'Heavy Tipper Multi-Axle Driver', month: 'March 2026', workingDays: 27, basic: 22000, overtime: 2100, batta: 7200, allowances: 2000, advanceDeduction: 1500, otherDeductions: 1500, grossSalary: 33300, netSalary: 30300, status: 'Approved', paymentMode: 'Bank Transfer' },
  { id: 'PAY-2026-03-04', employeeId: 'EMP-004', employeeName: 'Anjali Menon', department: 'Accounts & Finance', designation: 'Senior Accountant', month: 'March 2026', workingDays: 26, basic: 38000, overtime: 0, batta: 0, allowances: 5000, advanceDeduction: 0, otherDeductions: 2500, grossSalary: 43000, netSalary: 40500, status: 'Paid', paymentDate: '2026-03-20', paymentMode: 'Bank Transfer' },
  { id: 'PAY-2026-03-05', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', designation: 'Heavy Excavator Operator', month: 'March 2026', workingDays: 24, basic: 24200, overtime: 1950, batta: 3300, allowances: 1500, advanceDeduction: 1000, otherDeductions: 1200, grossSalary: 30950, netSalary: 28750, status: 'Calculated', paymentMode: 'Bank Transfer' },
  { id: 'PAY-2026-03-06', employeeId: 'EMP-006', employeeName: 'Kiran Dev', department: 'Dispatch & Weighbridge', designation: 'Weighbridge & Gate Officer', month: 'March 2026', workingDays: 26, basic: 21000, overtime: 850, batta: 0, allowances: 2000, advanceDeduction: 1000, otherDeductions: 1400, grossSalary: 23850, netSalary: 21450, status: 'Draft', paymentMode: 'Bank Transfer' }
];

export const MOCK_STAFF_ADVANCES: StaffAdvance[] = [
  { id: 'ADV-2026-001', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', advanceDate: '2026-01-10', purpose: 'Home electrical wiring and renovation', advanceAmount: 10000, recoveredAmount: 6000, balance: 4000, recoveryPlan: '₹1,000 / month salary deduction', monthlyDeduction: 1000, status: 'Active' },
  { id: 'ADV-2026-002', employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', advanceDate: '2026-02-05', purpose: 'Children school fees installment', advanceAmount: 5000, recoveredAmount: 3500, balance: 1500, recoveryPlan: '₹1,000 / month salary deduction', monthlyDeduction: 1000, status: 'Active' },
  { id: 'ADV-2026-003', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', advanceDate: '2026-02-18', purpose: 'Two wheeler down payment loan', advanceAmount: 8000, recoveredAmount: 3000, balance: 5000, recoveryPlan: '₹1,500 / month salary deduction', monthlyDeduction: 1500, status: 'Active' },
  { id: 'ADV-2026-004', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', advanceDate: '2026-03-01', purpose: 'Family medical dental treatment', advanceAmount: 4000, recoveredAmount: 2000, balance: 2000, recoveryPlan: '₹1,000 / month salary deduction', monthlyDeduction: 1000, status: 'Active' },
  { id: 'ADV-2026-005', employeeId: 'EMP-006', employeeName: 'Kiran Dev', department: 'Dispatch & Weighbridge', advanceDate: '2026-03-12', purpose: 'Bike tire replacement and insurance', advanceAmount: 2000, recoveredAmount: 1000, balance: 1000, recoveryPlan: '₹1,000 / month salary deduction', monthlyDeduction: 1000, status: 'Active' },
  { id: 'ADV-2026-006', employeeId: 'EMP-008', employeeName: 'Muhammed Shafi', department: 'Quarry Operations', advanceDate: '2026-02-10', purpose: 'Daughter college admission deposit', advanceAmount: 12000, recoveredAmount: 6000, balance: 6000, recoveryPlan: '₹2,000 / month salary deduction', monthlyDeduction: 2000, status: 'Active' }
];

export const MOCK_BATTA_ENTRIES: BattaEntry[] = [
  { id: 'BAT-091', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', type: 'Trip Batta', date: '2026-03-24', reference: 'TRIP-2026-881 (Kochi Bypass 40-Ton Tipper)', amount: 600, vehicleNo: 'KL-11-BH-9821', status: 'Approved', approvedBy: 'Babu Moopan' },
  { id: 'BAT-092', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', type: 'Daily Allowance', date: '2026-03-24', reference: 'Pithead Safety Inspection & Mining Audit', amount: 350, status: 'Approved', approvedBy: 'Nafid Khan (MD)' },
  { id: 'BAT-093', employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', type: 'Food Allowance', date: '2026-03-24', reference: 'Overtime Night Crusher Maintenance Support', amount: 400, status: 'Approved', approvedBy: 'Eng. Sudheer Babu' },
  { id: 'BAT-094', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', type: 'Night Halt', date: '2026-03-23', reference: 'TRIP-2026-879 (Wayanad Sand Inward Haulage)', amount: 800, vehicleNo: 'KL-11-BH-9821', status: 'Paid', approvedBy: 'Babu Moopan' },
  { id: 'BAT-095', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', type: 'Daily Allowance', date: '2026-03-24', reference: 'Excavator Rock Hammering Shift Batta', amount: 300, status: 'Pending' }
];

export const MOCK_STAFF_DOCUMENTS: StaffDocument[] = [
  { id: 'DOC-01', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', title: 'Aadhaar Card National ID', category: 'ID Proof', documentNumber: 'XXXX-XXXX-8921', issueDate: '2018-04-12', expiryDate: '2035-12-31', status: 'Valid' },
  { id: 'DOC-02', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', title: 'DGMS Mining Supervisor Competency Certificate', category: 'Certification', documentNumber: 'DGMS-SZ-2019-482', issueDate: '2019-06-15', expiryDate: '2026-06-14', status: 'Expiring Soon' },
  { id: 'DOC-03', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', title: 'Heavy Transport Driving License (HMV+Badge)', category: 'License', documentNumber: 'KL-11-20120008492', issueDate: '2012-08-10', expiryDate: '2026-04-10', status: 'Expiring Soon' },
  { id: 'DOC-04', employeeId: 'EMP-008', employeeName: 'Muhammed Shafi', department: 'Quarry Operations', title: 'Controller of Explosives Shot Firer License', category: 'License', documentNumber: 'PESO-KER-BLAST-991', issueDate: '2021-02-14', expiryDate: '2026-03-31', status: 'Expiring Soon' },
  { id: 'DOC-05', employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', title: 'High Voltage Plant Electrician Wireman License', category: 'Certification', documentNumber: 'KSEB-WL-49281', issueDate: '2020-03-11', expiryDate: '2028-03-10', status: 'Valid' },
  { id: 'DOC-06', employeeId: 'EMP-004', employeeName: 'Anjali Menon', department: 'Accounts & Finance', title: 'PAN Card Tax Registration', category: 'ID Proof', documentNumber: 'AAECM9921D', issueDate: '2016-07-22', expiryDate: '2099-12-31', status: 'Valid' },
  { id: 'DOC-07', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', title: 'Heavy Earth Moving Machinery (HEMM) Operator Certificate', category: 'Certification', documentNumber: 'HEMM-EXC-2021-98', issueDate: '2021-05-10', expiryDate: '2024-05-09', status: 'Expired' }
];

export const MOCK_WORKFORCE_APPROVALS: WorkforceApproval[] = [
  { id: 'APP-01', type: 'Leave', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', date: '2026-03-24', amountOrDays: '2 Days (Sick Leave)', requestedBy: 'Suresh Babu', details: 'Viral fever consultation medical rest', status: 'Pending' },
  { id: 'APP-02', type: 'Overtime', employeeId: 'EMP-002', employeeName: 'Mustafa K.', department: 'Crusher Plant', date: '2026-03-24', amountOrDays: '1.7 Hours (₹340)', requestedBy: 'Mustafa K.', details: 'VSI sand screen bearing greasing & emergency belt tensioning', status: 'Pending' },
  { id: 'APP-03', type: 'Staff Advance', employeeId: 'EMP-006', employeeName: 'Kiran Dev', department: 'Dispatch & Weighbridge', date: '2026-03-23', amountOrDays: '₹2,000 Advance', requestedBy: 'Kiran Dev', details: 'Two-wheeler tire replacement and brake repair loan', status: 'Pending' },
  { id: 'APP-04', type: 'Batta', employeeId: 'EMP-005', employeeName: 'Suresh Babu', department: 'Quarry Operations', date: '2026-03-24', amountOrDays: '₹300 Batta', requestedBy: 'Rajesh Nair', details: 'Pithead boulder secondary breaking overtime batta', status: 'Pending' },
  { id: 'APP-05', type: 'Salary', employeeId: 'EMP-001', employeeName: 'Rajesh Nair', department: 'Quarry Operations', date: '2026-03-24', amountOrDays: '₹34,240 Net Salary', requestedBy: 'Anjali Menon (Accounts)', details: 'Monthly payroll batch clearance for Quarry pithead team', status: 'Pending' },
  { id: 'APP-06', type: 'Documents', employeeId: 'EMP-003', employeeName: 'Arun Varma', department: 'Vehicle & Fleet Logistics', date: '2026-03-24', amountOrDays: 'HMV Driving License Renewal', requestedBy: 'Sunita Rao (HR)', details: 'RTO Kozhikode fitness test passing certificate renewal', status: 'Pending' }
];
